import { mkdir, writeFile, rename, readFile, readdir, unlink, stat } from 'node:fs/promises'
import { randomBytes } from 'node:crypto'
import { join } from 'node:path'
import type { Message, Usage } from '@zuse/core'
import { emptyUsage } from '@zuse/core'
import type { SessionMeta } from '@zuse/protocol'
import type { SessionCheckpoint } from './events.js'

// SessionMeta lives in @zuse/protocol (the single source-of-truth shape shared
// with the web client). Re-export it here so existing import sites under
// @zuse/server keep working unchanged.
export type { SessionMeta } from '@zuse/protocol'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SessionRecord {
  version: 1
  id: string
  title: string
  /** True when the title was set manually via rename() — keeps autosave's
   *  deriveTitle from clobbering a user-chosen title. */
  titleManual?: boolean
  /** True when the title was generated by the small model — pins it (no deriveTitle
   *  overwrite, no re-generation), but a manual rename still wins over it. */
  titleGenerated?: boolean
  cwd: string
  model?: string
  createdAt: string
  updatedAt: string
  messages: Message[]
  totalUsage: Usage
  checkpoints: SessionCheckpoint[]
}

// ---------------------------------------------------------------------------
// ID generation
// ---------------------------------------------------------------------------

/**
 * Generate a time-sortable session id: YYYYMMDD-HHMMSS-<4 hex chars>.
 * Pass `now` to get deterministic output in tests.
 */
export function newSessionId(now: Date = new Date()): string {
  const pad = (n: number): string => String(n).padStart(2, '0')
  const ts =
    `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}` +
    `-${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`
  // 8 hex chars (32 bits) of CRYPTO randomness. The old 16-bit Math.random() suffix collided
  // ~1/65535 for two creates in the same second — and saveSession overwrites on collision, so
  // a clash silently destroyed a session. 32 crypto bits makes a same-second clash negligible.
  const rand = randomBytes(4).toString('hex')
  return `${ts}-${rand}`
}

// ---------------------------------------------------------------------------
// Path safety
// ---------------------------------------------------------------------------

/**
 * Guard against path traversal: id must consist only of alphanumerics and hyphens.
 * newSessionId always produces safe ids; this is a belt-and-suspenders check for
 * ids that arrive from external sources (e.g. HTTP request params).
 */
function safeId(id: string): string {
  if (!/^[a-zA-Z0-9-]+$/.test(id)) {
    throw new Error(`Invalid session id (contains unsafe characters): "${id}"`)
  }
  return id
}

// ---------------------------------------------------------------------------
// Core CRUD
// ---------------------------------------------------------------------------

/**
 * Atomically persist a session record.
 * Writes to `<id>.json.tmp` first, then renames to `<id>.json` so a crash
 * mid-write never leaves a corrupt final file.
 */
export async function saveSession(dir: string, rec: SessionRecord): Promise<void> {
  await mkdir(dir, { recursive: true })
  const safe = safeId(rec.id)
  const finalPath = join(dir, `${safe}.json`)
  const tmpPath = `${finalPath}.tmp`
  await writeFile(tmpPath, JSON.stringify(rec, null, 2), 'utf8')
  await rename(tmpPath, finalPath)
}

/**
 * Load a session by id. Returns null if the file is missing or unparseable.
 * Throws on invalid ids (path-safety enforcement is not swallowed).
 */
export async function loadSession(dir: string, id: string): Promise<SessionRecord | null> {
  // safeId throws synchronously on bad input — let it propagate.
  const safe = safeId(id)
  try {
    const raw = await readFile(join(dir, `${safe}.json`), 'utf8')
    return JSON.parse(raw) as SessionRecord
  } catch {
    return null
  }
}

/**
 * Cache so listSessions doesn't re-read+JSON.parse every session's FULL record (which
 * carries the entire messages[] array — hundreds of KB each) on every call. The web client
 * calls listSessions on every turn-end to refresh the sidebar; without this, each refresh is
 * O(total bytes of all conversations). Keyed by file path → its mtime; a session's metadata
 * is only re-parsed when its file actually changes (i.e. the one session just written this
 * turn), turning per-turn cost from "parse N files" into "stat N files + parse 1".
 */
const metaCache = new Map<string, { mtimeMs: number; meta: SessionMeta }>()

/**
 * List all sessions in `dir` as lightweight metadata objects, sorted by
 * `updatedAt` descending. Corrupt or incomplete files are silently skipped.
 * Returns [] if the directory does not exist.
 */
export async function listSessions(dir: string): Promise<SessionMeta[]> {
  let files: string[]
  try {
    files = (await readdir(dir)).filter((f) => f.endsWith('.json'))
  } catch {
    // Directory doesn't exist — no sessions yet.
    return []
  }

  const seen = new Set<string>()
  const metas: SessionMeta[] = []
  for (const f of files) {
    const path = join(dir, f)
    seen.add(path)
    try {
      const mtimeMs = (await stat(path)).mtimeMs
      const cached = metaCache.get(path)
      if (cached && cached.mtimeMs === mtimeMs) {
        metas.push(cached.meta)
        continue
      }
      const raw = await readFile(path, 'utf8')
      const rec = JSON.parse(raw) as Partial<SessionRecord>
      // Require the fields that make a SessionMeta meaningful.
      if (
        typeof rec.id !== 'string' ||
        typeof rec.title !== 'string' ||
        typeof rec.createdAt !== 'string' ||
        typeof rec.updatedAt !== 'string' ||
        typeof rec.cwd !== 'string' ||
        !Array.isArray(rec.messages)
      ) {
        continue
      }
      const meta: SessionMeta = {
        id: rec.id,
        title: rec.title,
        createdAt: rec.createdAt,
        updatedAt: rec.updatedAt,
        cwd: rec.cwd,
        messageCount: rec.messages.length,
      }
      metaCache.set(path, { mtimeMs, meta })
      metas.push(meta)
    } catch {
      // Corrupt or vanished file — skip.
      continue
    }
  }
  // Drop cache entries for sessions that no longer exist (deleted), so the map can't grow without bound.
  for (const path of metaCache.keys()) if (!seen.has(path)) metaCache.delete(path)

  metas.sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : -1))
  return metas
}

/** One session's recorded token usage, for the M5 dashboard's aggregation. */
export interface SessionUsageRow {
  id: string
  title: string
  /** '' when the record never persisted a model. */
  model: string
  updatedAt: string
  totalUsage: Usage
}

/** Coerce a possibly-missing/partial persisted usage into a full Usage (missing fields → 0). */
function normalizeUsage(u: Partial<Usage> | undefined): Usage {
  const base = emptyUsage()
  if (!u) return base
  return {
    input_tokens: u.input_tokens ?? 0,
    output_tokens: u.output_tokens ?? 0,
    cache_read_input_tokens: u.cache_read_input_tokens ?? 0,
    cache_creation_input_tokens: u.cache_creation_input_tokens ?? 0,
  }
}

/**
 * Read every session record's token usage (M5). Reads the same files as listSessions but keeps
 * the usage + model fields it drops. Corrupt/foreign files are skipped. No sorting — the caller
 * (UsageService) aggregates and orders.
 */
export async function readSessionUsage(dir: string): Promise<SessionUsageRow[]> {
  let files: string[]
  try {
    files = (await readdir(dir)).filter((f) => f.endsWith('.json'))
  } catch {
    return []
  }
  // Read + parse the session files concurrently — the dashboard aggregates every session, so a
  // serial loop would be one disk round-trip per file. Corrupt/foreign files resolve to null.
  const settled = await Promise.all(
    files.map(async (f): Promise<SessionUsageRow | null> => {
      try {
        const rec = JSON.parse(await readFile(join(dir, f), 'utf8')) as Partial<SessionRecord>
        if (typeof rec.id !== 'string') return null
        return {
          id: rec.id,
          title: typeof rec.title === 'string' ? rec.title : '',
          model: typeof rec.model === 'string' ? rec.model : '',
          updatedAt: typeof rec.updatedAt === 'string' ? rec.updatedAt : '',
          totalUsage: normalizeUsage(rec.totalUsage),
        }
      } catch {
        return null
      }
    }),
  )
  return settled.filter((r): r is SessionUsageRow => r !== null)
}

/**
 * Delete a session file. Missing files are silently ignored (idempotent).
 */
export async function deleteSession(dir: string, id: string): Promise<void> {
  try {
    await unlink(join(dir, `${safeId(id)}.json`))
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err
  }
}
